### ISSUE TITLE
DI instead of Object Manager

### ISSUE THREAD

**Issue by WaPoNe** [sitewards/setup-mage2#10]
Why don't you use **DI** instead of **Object Manager** in _Application_ > _Bridge.php_ file?

```
/** @var ObjectManager */
private $objectManager;
..
$this->objectManager = ObjectManager::getInstance();
..
$this->objectManager->get(\Magento\Cms\Api\PageRepositoryInterface::class),
$this->objectManager->get(\Magento\Framework\Api\SearchCriteriaBuilder::class),
$this->objectManager->get(\Magento\Cms\Api\Data\PageInterfaceFactory::class)
```

**Comment by dpoposki** [comment]
The Bridge class is a bootstrap point of the module. We use the object manager in order to delegate the responsibility of instantiating the Magento objects to Magento itself. We do use DI when instantiating the PageRepository class by sending the three Magento objects which we've created with the manager (the last three lines of your snippet). What would you do differently? Can you give us a concrete example?

**Comment by WaPoNe** [comment]
Oh, ok!
Now I understand your implementation choice.
